// foodDatabase.js
// 'Can I eat this?' data, ported from the native Bloom app. Written from public
// guidance (FDA, EPA, CDC, ACOG, Mayo Clinic, NHS). Informational only.
// Preparation variations (cooked/raw, pasteurized/unpasteurized) are separate
// entries so a search lands on the specific form asked about.

const FOOD_DB = [
  {
    name: "Coffee",
    verdict: "caution",
    summary: "Yes, but keep caffeine under about 200 mg a day — roughly one to two cups of brewed coffee.",
    why: "Caffeine crosses the placenta, and the baby can't process it efficiently. Higher intakes are linked in some studies to lower birth weight and miscarriage risk.",
    safeWhen: "Stay under ~200 mg of caffeine a day from all sources combined.",
    aliases: ["caffeine", "latte", "espresso", "cappuccino", "americano", "cold brew", "mocha"],
    source: "ACOG",
    category: "Drinks",
  },
  {
    name: "Decaf coffee",
    verdict: "safe",
    summary: "Yes — decaf is fine. It has only a few milligrams of caffeine per cup.",
    why: "Decaffeinated coffee contains minimal caffeine and poses no special concern in pregnancy.",
    aliases: ["decaffeinated coffee"],
    source: "Mayo Clinic",
    category: "Drinks",
  },
  {
    name: "Black or green tea",
    verdict: "caution",
    summary: "Fine in moderation — count it toward your daily caffeine limit.",
    why: "Black tea has roughly 40-60 mg of caffeine per cup and green tea 12-30 mg, which adds to your daily total.",
    safeWhen: "Enjoy a few cups while keeping total caffeine under ~200 mg a day.",
    aliases: ["black tea", "green tea", "chai", "matcha"],
    source: "Mayo Clinic",
    category: "Drinks",
  },
  {
    name: "Herbal tea",
    verdict: "caution",
    summary: "Depends on the herb. Ginger and peppermint are widely considered safe; many blends haven't been studied.",
    why: "Not all herbal ingredients are tested for pregnancy safety. Ginger and peppermint have reassuring records and can ease nausea.",
    safeWhen: "Stick to ginger or peppermint in normal amounts; check other blends with your provider.",
    aliases: ["peppermint tea", "ginger tea", "chamomile tea", "raspberry leaf tea"],
    source: "NHS",
    category: "Drinks",
  },
  {
    name: "Alcohol",
    verdict: "avoid",
    summary: "No amount of alcohol is considered safe at any point in pregnancy.",
    why: "Alcohol crosses the placenta freely and is linked to fetal alcohol spectrum disorders, developmental delays, and birth defects.",
    aliases: ["wine", "beer", "spirits", "cocktail", "champagne", "liquor", "prosecco", "whiskey", "vodka"],
    source: "ACOG & CDC",
    category: "Drinks",
  },
  {
    name: "Energy drinks",
    verdict: "avoid",
    summary: "Best avoided — they combine high caffeine with other stimulants.",
    why: "Energy drinks often exceed safe caffeine levels and add ingredients like taurine and guarana that aren't well studied in pregnancy.",
    aliases: ["red bull", "monster", "energy drink"],
    source: "NHS",
    category: "Drinks",
  },
  {
    name: "Diet and regular soda",
    verdict: "caution",
    summary: "Okay occasionally — mind the caffeine in colas and keep added sugar modest.",
    why: "Colas contain caffeine that counts toward your daily limit. Artificial sweeteners in normal amounts are considered acceptable.",
    safeWhen: "Limit caffeinated sodas and treat sugary drinks as an occasional thing.",
    aliases: ["soda", "cola", "diet coke", "pop", "soft drink"],
    source: "ACOG",
    category: "Drinks",
  },
  {
    name: "Unpasteurized juice or cider",
    verdict: "avoid",
    summary: "Skip fresh-squeezed or unpasteurized juice and cider; pasteurized versions are fine.",
    why: "Raw juice can carry E. coli, salmonella, or other bacteria. Pasteurization removes the risk.",
    safeWhen: "Pasteurized juice — most bottled and packaged juice — is safe.",
    aliases: ["fresh juice", "apple cider", "raw juice", "cold pressed juice"],
    source: "FDA",
    category: "Drinks",
  },
  {
    name: "Pasteurized milk",
    verdict: "safe",
    summary: "Yes — pasteurized milk is safe and a good source of calcium.",
    why: "Pasteurization removes the bacteria that make raw milk risky. Whole, low-fat, and skim are all fine.",
    aliases: ["milk", "whole milk", "skim milk", "2% milk"],
    source: "FDA",
    category: "Drinks",
  },
  {
    name: "Unpasteurized (raw) milk",
    verdict: "avoid",
    summary: "Avoid raw milk and anything made from it.",
    why: "Unpasteurized milk can carry listeria, E. coli, and salmonella. Pasteurization is the only way to remove these.",
    safeWhen: "All pasteurized milk — the standard in stores — is safe.",
    aliases: ["raw milk", "unpasteurized milk"],
    source: "FDA",
    category: "Drinks",
  },
  {
    name: "Smoothies",
    verdict: "safe",
    summary: "Yes — homemade or from pasteurized ingredients, they're a great way to get nutrients.",
    why: "Smoothies are fine as long as the dairy and juice in them are pasteurized and any produce is washed.",
    safeWhen: "Use pasteurized milk or yogurt and washed fruit.",
    aliases: ["smoothie", "protein shake"],
    source: "NHS",
    category: "Drinks",
  },
  {
    name: "Kombucha",
    verdict: "caution",
    summary: "Best limited or avoided — it's fermented, often unpasteurized, and slightly alcoholic.",
    why: "Kombucha is typically raw and can contain trace alcohol and unpredictable bacteria from fermentation.",
    safeWhen: "If you have it, choose pasteurized versions and keep it occasional.",
    aliases: ["kombucha", "fermented tea"],
    source: "Mayo Clinic",
    category: "Drinks",
  },
  {
    name: "Cooked salmon",
    verdict: "safe",
    summary: "Yes — cooked salmon is a 'Best Choice', low in mercury and rich in omega-3s.",
    why: "Salmon supports the baby's brain and eye development and is among the most recommended fish in pregnancy.",
    safeWhen: "Cook to 145°F, until it flakes.",
    aliases: ["salmon", "baked salmon", "grilled salmon"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Raw salmon or sushi-grade fish",
    verdict: "avoid",
    summary: "Avoid raw fish — but the same fish fully cooked is a great choice.",
    why: "Raw fish can carry parasites and bacteria like listeria, riskier in pregnancy. Cooking eliminates them.",
    safeWhen: "Fully cooked, it's safe and recommended.",
    aliases: ["raw salmon", "sashimi", "sushi grade", "crudo"],
    source: "ACOG",
    category: "Seafood",
  },
  {
    name: "Shrimp",
    verdict: "safe",
    summary: "Yes — cooked shrimp is low-mercury and a 'Best Choice'.",
    why: "Shrimp is among the lowest-mercury seafood and a good protein source.",
    safeWhen: "Cook until opaque; avoid raw shrimp.",
    aliases: ["prawns", "cooked shrimp"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Canned light tuna",
    verdict: "safe",
    summary: "Yes — canned light tuna is a 'Best Choice'. Enjoy 2-3 servings a week.",
    why: "Canned light tuna is low in mercury, unlike albacore.",
    aliases: ["light tuna", "tinned tuna", "canned tuna", "skipjack"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Albacore (white) tuna",
    verdict: "caution",
    summary: "Limit to one serving (about 6 oz) a week — about three times the mercury of light tuna.",
    why: "Albacore carries more mercury, which can affect the baby's developing nervous system.",
    safeWhen: "One serving per week, with no other higher-mercury fish that week.",
    aliases: ["white tuna", "albacore", "tuna steak"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Shark, swordfish, king mackerel, marlin",
    verdict: "avoid",
    summary: "Avoid these — they carry the highest mercury of common fish.",
    why: "These large predatory fish accumulate the most methylmercury, which can harm the baby's developing brain.",
    aliases: ["shark", "swordfish", "king mackerel", "marlin", "tilefish", "orange roughy", "bigeye tuna"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Cooked sushi rolls",
    verdict: "safe",
    summary: "Yes — rolls made with cooked fish or veggies (California roll, shrimp tempura, eel) are fine.",
    why: "Cooked sushi carries none of the raw-fish risk. The rice and seaweed are fine.",
    safeWhen: "Choose cooked or vegetarian rolls; skip raw fish.",
    aliases: ["california roll", "cooked sushi", "veggie roll", "tempura roll"],
    source: "ACOG",
    category: "Seafood",
  },
  {
    name: "Smoked seafood (lox)",
    verdict: "avoid",
    summary: "Avoid refrigerated smoked fish unless cooked into a dish.",
    why: "Cold-smoked, refrigerated seafood can harbor listeria. Heat destroys it.",
    safeWhen: "Smoked fish baked into a casserole is fine; canned, shelf-stable versions too.",
    aliases: ["lox", "smoked salmon", "nova", "kippers"],
    source: "Mayo Clinic",
    category: "Seafood",
  },
  {
    name: "Crab and lobster",
    verdict: "safe",
    summary: "Yes — cooked crab and lobster are low-mercury 'Best Choices'.",
    why: "Properly cooked, they're low in mercury and safe. Imitation crab is cooked and fine too.",
    safeWhen: "Cook thoroughly; avoid raw.",
    aliases: ["lobster", "crab", "crab legs", "imitation crab", "crawfish"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Cooked oysters, mussels, clams",
    verdict: "caution",
    summary: "Okay when thoroughly cooked; never raw.",
    why: "Cooked shellfish is safe, but raw shellfish is a leading cause of foodborne illness and must be avoided.",
    safeWhen: "Cook until the shells open and the flesh is firm.",
    aliases: ["mussels", "clams", "cooked oysters", "scallops"],
    source: "FDA",
    category: "Seafood",
  },
  {
    name: "Raw oysters and raw shellfish",
    verdict: "avoid",
    summary: "Avoid all raw shellfish.",
    why: "Raw oysters, clams, and mussels can carry vibrio, norovirus, and other pathogens that are dangerous in pregnancy.",
    safeWhen: "Fully cooked, these become safe.",
    aliases: ["raw oysters", "raw clams", "ceviche", "oysters on the half shell"],
    source: "FDA",
    category: "Seafood",
  },
  {
    name: "Canned or cooked sardines and anchovies",
    verdict: "safe",
    summary: "Yes — these small fish are low-mercury and rich in omega-3s and calcium.",
    why: "Small, short-lived fish accumulate little mercury and are a 'Best Choice'.",
    aliases: ["sardines", "anchovies"],
    source: "FDA & EPA",
    category: "Seafood",
  },
  {
    name: "Soft cheese made with pasteurized milk",
    verdict: "safe",
    summary: "Yes — brie, camembert, feta, and goat cheese are fine if made with pasteurized milk. Check the label.",
    why: "The listeria risk in soft cheese comes from unpasteurized milk. ACOG notes soft cheeses made with pasteurized milk are safe.",
    safeWhen: "Look for 'made with pasteurized milk' on the label.",
    aliases: ["brie", "camembert", "feta", "goat cheese", "queso fresco", "pasteurized soft cheese"],
    source: "ACOG",
    category: "Cheese & dairy",
  },
  {
    name: "Soft cheese made with unpasteurized milk",
    verdict: "avoid",
    summary: "Avoid soft cheeses made from raw (unpasteurized) milk.",
    why: "Unpasteurized soft cheeses can carry listeria, which is far more dangerous in pregnancy.",
    safeWhen: "Heating until steaming hot makes it safe, or choose a pasteurized version.",
    aliases: ["raw milk cheese", "unpasteurized cheese", "queso fresco unpasteurized"],
    source: "CDC",
    category: "Cheese & dairy",
  },
  {
    name: "Blue cheese",
    verdict: "caution",
    summary: "Best avoided unless it's made with pasteurized milk and cooked, since many blues are mold-ripened.",
    why: "Soft, mold-ripened blue cheeses can support listeria growth. Pasteurized, cooked-in versions lower the risk.",
    safeWhen: "Cooked into a sauce or made with pasteurized milk, it's safer.",
    aliases: ["blue cheese", "gorgonzola", "roquefort", "stilton"],
    source: "NHS",
    category: "Cheese & dairy",
  },
  {
    name: "Hard cheese",
    verdict: "safe",
    summary: "Yes — cheddar, parmesan, swiss, gouda, and the like are safe.",
    why: "Hard cheeses are low-risk for listeria, especially when made with pasteurized milk.",
    aliases: ["cheddar", "parmesan", "swiss", "gouda", "manchego", "hard cheese"],
    source: "CDC",
    category: "Cheese & dairy",
  },
  {
    name: "Mozzarella and pasteurized soft cheeses",
    verdict: "safe",
    summary: "Yes — pasteurized mozzarella, cream cheese, cottage cheese, and ricotta are safe.",
    why: "These are made from pasteurized milk and are low-risk.",
    aliases: ["mozzarella", "cream cheese", "cottage cheese", "ricotta", "string cheese", "paneer"],
    source: "CDC",
    category: "Cheese & dairy",
  },
  {
    name: "Yogurt",
    verdict: "safe",
    summary: "Yes — pasteurized yogurt, including Greek yogurt, is a great choice.",
    why: "Commercial yogurt is made from pasteurized milk and provides protein and probiotics.",
    aliases: ["yogurt", "greek yogurt", "skyr"],
    source: "NHS",
    category: "Cheese & dairy",
  },
  {
    name: "Ice cream",
    verdict: "safe",
    summary: "Yes — store-bought ice cream is made with pasteurized ingredients.",
    why: "Commercial ice cream is pasteurized. Homemade versions with raw egg are the exception.",
    safeWhen: "Avoid homemade ice cream made with raw eggs.",
    aliases: ["ice cream", "gelato", "frozen yogurt"],
    source: "FDA",
    category: "Cheese & dairy",
  },
  {
    name: "Cooked deli meat (heated)",
    verdict: "safe",
    summary: "Yes — when heated until steaming hot (165°F) right before eating.",
    why: "Heating destroys any listeria that can grow on ready-to-eat meats after packaging.",
    safeWhen: "Heat until steaming, then it's safe.",
    aliases: ["heated deli meat", "hot deli meat", "toasted sandwich"],
    source: "CDC",
    category: "Meat & eggs",
  },
  {
    name: "Cold deli meat and cold cuts",
    verdict: "caution",
    summary: "Best avoided cold; heat until steaming first.",
    why: "Ready-to-eat deli meats and cold cuts can carry listeria from handling and storage.",
    safeWhen: "Heat until steaming hot just before eating.",
    aliases: ["lunch meat", "cold cuts", "ham", "turkey slices", "salami", "bologna", "deli meat", "prosciutto", "mortadella"],
    source: "CDC",
    category: "Meat & eggs",
  },
  {
    name: "Hot dogs",
    verdict: "caution",
    summary: "Okay only when heated until steaming hot.",
    why: "Like deli meats, hot dogs can carry listeria and need thorough reheating.",
    safeWhen: "Heat until steaming; avoid eating straight from the package.",
    aliases: ["hot dog", "frankfurter", "wiener"],
    source: "CDC",
    category: "Meat & eggs",
  },
  {
    name: "Thoroughly cooked beef, pork, chicken",
    verdict: "safe",
    summary: "Yes — as long as it's cooked through to a safe temperature.",
    why: "Thorough cooking kills toxoplasma, salmonella, and E. coli. Raw or undercooked meat can carry them.",
    safeWhen: "Whole cuts 145°F, ground 160°F, poultry 165°F.",
    aliases: ["beef", "chicken", "pork", "steak", "turkey", "meat", "cooked chicken"],
    source: "USDA",
    category: "Meat & eggs",
  },
  {
    name: "Rare or undercooked meat",
    verdict: "avoid",
    summary: "Avoid rare, pink, or raw meat — cook it through.",
    why: "Undercooked meat can carry toxoplasma and bacteria that cross the placenta. Visual checks aren't reliable enough.",
    safeWhen: "Use a thermometer: 145°F whole cuts, 160°F ground, 165°F poultry.",
    aliases: ["rare steak", "raw meat", "steak tartare", "medium rare", "carpaccio"],
    source: "USDA",
    category: "Meat & eggs",
  },
  {
    name: "Fully cooked eggs",
    verdict: "safe",
    summary: "Yes — cook until the yolk and white are firm.",
    why: "Thoroughly cooked eggs are safe; runny eggs can carry salmonella.",
    safeWhen: "Cook until set; for runny dishes use pasteurized eggs.",
    aliases: ["eggs", "scrambled eggs", "hard boiled", "omelette"],
    source: "Mayo Clinic",
    category: "Meat & eggs",
  },
  {
    name: "Runny or raw eggs",
    verdict: "caution",
    summary: "Use pasteurized eggs for anything runny or raw.",
    why: "Raw or undercooked eggs can carry salmonella, which can cause illness and, rarely, preterm labor.",
    safeWhen: "Pasteurized eggs are safe even soft-cooked; otherwise cook until firm.",
    aliases: ["runny eggs", "raw egg", "soft boiled", "sunny side up", "poached egg", "cookie dough", "homemade mayo", "hollandaise", "caesar dressing", "eggnog"],
    source: "Mayo Clinic",
    category: "Meat & eggs",
  },
  {
    name: "Pâté and refrigerated meat spreads",
    verdict: "avoid",
    summary: "Avoid refrigerated pâté and meat spreads; canned, shelf-stable versions are fine.",
    why: "Refrigerated meat spreads can carry listeria. Shelf-stable canned ones are processed to be safe.",
    safeWhen: "Canned or cooked-into-a-dish is fine.",
    aliases: ["pate", "meat spread", "liverwurst"],
    source: "Mayo Clinic",
    category: "Meat & eggs",
  },
  {
    name: "Cured or fermented sausage (salami, pepperoni)",
    verdict: "caution",
    summary: "Cook it — on a hot pizza or heated — rather than eating cold.",
    why: "Cured but uncooked sausages can carry listeria or toxoplasma.",
    safeWhen: "Thoroughly heated (e.g. on cooked pizza) it's fine.",
    aliases: ["salami", "pepperoni", "chorizo", "fermented sausage"],
    source: "NHS",
    category: "Meat & eggs",
  },
  {
    name: "Bacon",
    verdict: "safe",
    summary: "Yes — when cooked until crisp and no longer pink.",
    why: "Fully cooked bacon is fine. The usual rule against undercooked pork applies.",
    safeWhen: "Cook until crisp.",
    aliases: ["bacon", "pancetta"],
    source: "USDA",
    category: "Meat & eggs",
  },
  {
    name: "Liver and organ meat",
    verdict: "caution",
    summary: "Fine occasionally, but limit it — liver is very high in vitamin A.",
    why: "Too much preformed vitamin A (retinol), concentrated in liver, can harm the baby's development.",
    safeWhen: "Limit to a small serving no more than once a week.",
    aliases: ["liver", "organ meat", "pate liver", "kidney"],
    source: "NHS",
    category: "Meat & eggs",
  },
  {
    name: "Washed fruits and vegetables",
    verdict: "safe",
    summary: "Yes — just wash them thoroughly first.",
    why: "Produce is important in pregnancy. Unwashed surfaces can carry toxoplasma or soil bacteria.",
    safeWhen: "Rinse under running water; scrub firm items like melons before cutting.",
    aliases: ["fruit", "vegetables", "salad", "produce", "apple", "berries", "spinach"],
    source: "CDC",
    category: "Produce & other",
  },
  {
    name: "Pre-washed bagged salad",
    verdict: "caution",
    summary: "Generally fine, but give it another rinse and keep it cold.",
    why: "Bagged greens have occasionally been linked to listeria and E. coli outbreaks.",
    safeWhen: "Rinse before eating and keep refrigerated; avoid if past its date.",
    aliases: ["bagged salad", "pre washed greens", "spring mix"],
    source: "FDA",
    category: "Produce & other",
  },
  {
    name: "Raw sprouts",
    verdict: "avoid",
    summary: "Avoid raw sprouts — cook them thoroughly if you want them.",
    why: "Bacteria can grow inside sprout seeds before they sprout, and rinsing can't remove it.",
    safeWhen: "Thoroughly cooked sprouts are safe.",
    aliases: ["alfalfa sprouts", "bean sprouts", "sprouts", "mung beans"],
    source: "FDA",
    category: "Produce & other",
  },
  {
    name: "Melon (cantaloupe, honeydew)",
    verdict: "caution",
    summary: "Fine if washed well and eaten fresh; don't let cut melon sit out.",
    why: "Melon rinds can carry listeria or salmonella that's dragged into the flesh when cut.",
    safeWhen: "Scrub the rind before cutting; refrigerate and eat within a day or two.",
    aliases: ["cantaloupe", "honeydew", "watermelon", "melon"],
    source: "FDA",
    category: "Produce & other",
  },
  {
    name: "Honey",
    verdict: "safe",
    summary: "Yes — honey is safe for you during pregnancy.",
    why: "The infant-botulism concern with honey applies to babies under one year, not pregnant adults.",
    aliases: ["raw honey", "honey"],
    source: "NHS",
    category: "Produce & other",
  },
  {
    name: "Deli salads (chicken, tuna, egg)",
    verdict: "caution",
    summary: "Store-made refrigerated deli salads are best avoided; homemade is fine.",
    why: "Pre-made deli-counter salads can carry listeria from handling and storage.",
    safeWhen: "Made fresh at home with cooked, pasteurized ingredients, they're safe.",
    aliases: ["chicken salad", "tuna salad", "egg salad", "coleslaw", "potato salad"],
    source: "Mayo Clinic",
    category: "Produce & other",
  },
  {
    name: "Peanuts and nuts",
    verdict: "safe",
    summary: "Yes — unless you have a nut allergy, nuts are nutritious and fine.",
    why: "There's no need to avoid peanuts in pregnancy; older advice to do so has been reversed.",
    aliases: ["peanuts", "almonds", "nuts", "peanut butter", "cashews", "walnuts"],
    source: "NHS",
    category: "Produce & other",
  },
  {
    name: "Sushi rice and seaweed",
    verdict: "safe",
    summary: "Yes — rice, seaweed (nori), edamame, and avocado are all fine.",
    why: "The non-fish components of sushi carry no special risk.",
    aliases: ["nori", "seaweed", "edamame", "avocado roll", "rice"],
    source: "ACOG",
    category: "Produce & other",
  },
  {
    name: "Leftovers",
    verdict: "caution",
    summary: "Fine when refrigerated promptly and reheated until steaming hot.",
    why: "Listeria can grow slowly even in the fridge, so cooked leftovers should be eaten within a couple of days and reheated well.",
    safeWhen: "Refrigerate within two hours; eat within 2-3 days; reheat to steaming.",
    aliases: ["leftovers", "meal prep"],
    source: "CDC",
    category: "Produce & other",
  },
  {
    name: "Spicy food",
    verdict: "safe",
    summary: "Yes — spicy food is safe; it may just bring on heartburn.",
    why: "Spices don't harm the baby. Late in pregnancy they can aggravate reflux.",
    aliases: ["spicy food", "hot sauce", "curry", "chili"],
    source: "Mayo Clinic",
    category: "Produce & other",
  },
  {
    name: "Artificial sweeteners",
    verdict: "safe",
    summary: "Most are considered fine in normal amounts.",
    why: "Sweeteners like aspartame, sucralose, and stevia are regarded as acceptable in moderation during pregnancy.",
    safeWhen: "Enjoy in normal, moderate amounts.",
    aliases: ["aspartame", "sucralose", "stevia", "splenda", "sweetener"],
    source: "ACOG",
    category: "Produce & other",
  },
  {
    name: "Hot chocolate",
    verdict: "caution",
    summary: "Fine in moderation — it has some caffeine, so count it toward your daily limit.",
    why: "Cocoa contains a small amount of caffeine and a related stimulant, theobromine. The amounts are modest, but they add up alongside coffee, tea, and soda.",
    safeWhen: "Keep total caffeine under ~200 mg a day from all sources.",
    aliases: ["cocoa", "hot cocoa"],
    source: "ACOG",
    category: "Drinks",
  },
  {
    name: "Sparkling and mineral water",
    verdict: "safe",
    summary: "Yes — plain sparkling or mineral water is fine and a nice way to stay hydrated.",
    why: "Carbonation is harmless in pregnancy. Choose versions without added caffeine, and watch sodium only if your provider has advised limiting it.",
    aliases: ["seltzer", "soda water", "carbonated water", "fizzy water"],
    source: "Mayo Clinic",
    category: "Drinks",
  },
  {
    name: "Coconut water",
    verdict: "safe",
    summary: "Yes — a hydrating, naturally electrolyte-rich drink that’s fine during pregnancy.",
    why: "Coconut water is just a beverage with potassium and other electrolytes. It isn’t a treatment for anything, but it’s a perfectly good way to stay hydrated.",
    aliases: ["coconut juice"],
    category: "Drinks",
  },
  {
    name: "Canned or cooked tuna steak",
    verdict: "caution",
    summary: "Limit tuna steak and bigeye tuna — they run higher in mercury than canned light tuna.",
    why: "Larger tuna accumulate more mercury, which can affect a baby’s developing nervous system. Canned light tuna is lower and a better routine choice.",
    safeWhen: "Treat tuna steak like albacore: about 6 oz (one serving) per week at most.",
    aliases: ["tuna steak", "ahi", "bigeye tuna", "yellowfin"],
    source: "FDA/EPA",
    category: "Seafood",
  },
  {
    name: "Cod, tilapia, and other low-mercury fish",
    verdict: "safe",
    summary: "Yes — these are low-mercury \"best choices\" and great to eat 2–3 times a week.",
    why: "Fish is an excellent source of protein and omega-3s that support your baby’s brain and eye development. Low-mercury types are actively encouraged.",
    safeWhen: "Aim for 8–12 oz (two to three servings) of low-mercury fish per week.",
    aliases: ["cod", "tilapia", "pollock", "catfish", "haddock", "trout", "flounder"],
    source: "FDA/EPA",
    category: "Seafood",
  },
  {
    name: "Ceviche",
    verdict: "avoid",
    summary: "Skip it — the fish is \"cooked\" only by citrus, not heat, so the risk is like raw fish.",
    why: "Acid from lime or lemon changes the texture of the fish but doesn’t reliably kill parasites or bacteria the way heat does.",
    safeWhen: "Choose a fully cooked seafood dish instead.",
    aliases: ["raw fish", "sashimi", "poke", "tartare"],
    source: "FDA",
    category: "Seafood",
  },
  {
    name: "Caviar and fish roe",
    verdict: "caution",
    summary: "Pasteurized roe is fine; fresh, unpasteurized roe is best avoided.",
    why: "Like other ready-to-eat seafood, unpasteurized roe can carry listeria. Pasteurized or cooked roe (as in many cooked sushi rolls) removes that concern.",
    safeWhen: "Choose pasteurized roe, or roe that has been cooked.",
    aliases: ["roe", "tobiko", "ikura", "fish eggs"],
    category: "Seafood",
  },
  {
    name: "Feta cheese",
    verdict: "caution",
    summary: "Fine when it’s made from pasteurized milk — check the label, especially on imports and at delis.",
    why: "Soft, brined cheeses made from unpasteurized milk can carry listeria. Most supermarket feta is pasteurized and safe; deli or artisan feta may not be.",
    safeWhen: "Confirm it’s made with pasteurized milk, or use it cooked into a dish until steaming.",
    aliases: ["greek cheese"],
    source: "FDA",
    category: "Cheese & dairy",
  },
  {
    name: "Goat cheese",
    verdict: "caution",
    summary: "Pasteurized goat cheese is fine; the soft, rind-ripened kind from raw milk is best avoided.",
    why: "Soft and mould-ripened goat cheeses made from unpasteurized milk carry a listeria risk. Hard goat cheese and pasteurized versions are fine.",
    safeWhen: "Choose pasteurized, or cook it thoroughly.",
    aliases: ["chevre"],
    source: "NHS",
    category: "Cheese & dairy",
  },
  {
    name: "Brie and Camembert",
    verdict: "caution",
    summary: "Even pasteurized, these soft mould-ripened cheeses are safest cooked until steaming hot.",
    why: "Their moisture and surface mould make them more hospitable to listeria than hard cheeses, so guidance is cautious even when they’re pasteurized.",
    safeWhen: "Bake or cook until piping hot throughout, which kills listeria.",
    aliases: ["brie", "camembert", "soft ripened cheese"],
    source: "NHS",
    category: "Cheese & dairy",
  },
  {
    name: "Cottage cheese and cream cheese",
    verdict: "safe",
    summary: "Yes — these are made from pasteurized milk and are fine.",
    why: "Although soft, commercial cottage and cream cheese are produced from pasteurized milk and aren’t the mould-ripened type that raises concern.",
    aliases: ["cream cheese", "cottage cheese", "ricotta", "mascarpone"],
    source: "FDA",
    category: "Cheese & dairy",
  },
  {
    name: "Halloumi and paneer",
    verdict: "safe",
    summary: "Yes — these firm cheeses are pasteurized and usually eaten cooked.",
    why: "Halloumi and paneer are firm, low-risk cheeses, and they’re typically grilled or fried, which removes any concern.",
    aliases: ["halloumi", "paneer", "grilling cheese"],
    category: "Cheese & dairy",
  },
  {
    name: "Soft serve ice cream",
    verdict: "safe",
    summary: "Yes — soft serve from a reputable machine is made with pasteurized mix.",
    why: "Commercial soft serve uses pasteurized ingredients. The old worry was machine hygiene; choosing busy, clean outlets keeps it low risk.",
    aliases: ["frozen yogurt", "gelato", "soft serve"],
    source: "NHS",
    category: "Cheese & dairy",
  },
  {
    name: "Pasteurized eggs",
    verdict: "safe",
    summary: "Yes — pasteurized eggs are safe even in dishes where the egg stays soft.",
    why: "Pasteurization kills salmonella, so pasteurized eggs (often labelled, or shown by a red lion stamp in the UK) are fine lightly cooked.",
    safeWhen: "Look for \"pasteurized\" on the carton for recipes with runny or raw egg.",
    aliases: ["lion mark eggs", "safe eggs"],
    source: "ACOG",
    category: "Meat & eggs",
  },
  {
    name: "Raw cookie dough and cake batter",
    verdict: "avoid",
    summary: "Don’t eat it raw — both the raw egg and the raw flour are a problem.",
    why: "Raw egg can carry salmonella and raw flour can carry E. coli; neither is safe until baked. The risk isn’t just the egg.",
    safeWhen: "Bake fully, or use recipes made with heat-treated flour and pasteurized egg.",
    aliases: ["cookie dough", "cake batter", "brownie batter", "raw dough", "raw flour"],
    source: "CDC",
    category: "Meat & eggs",
  },
  {
    name: "Prosciutto and cured ham",
    verdict: "caution",
    summary: "Air-dried cured meats are safest cooked, or after freezing, because they’re not cooked in production.",
    why: "Cured but uncooked meats can carry toxoplasma and listeria. Cooking them, or home-freezing for a few days first, lowers the risk.",
    safeWhen: "Cook until hot (as on pizza), or freeze before eating.",
    aliases: ["prosciutto", "parma ham", "serrano", "chorizo", "cured ham"],
    source: "NHS",
    category: "Meat & eggs",
  },
  {
    name: "Game meat",
    verdict: "caution",
    summary: "Enjoy farmed venison and game cooked well; avoid game shot with lead and any rare cooking.",
    why: "Game can carry the same bugs as other meats and must be well cooked. Lead shot can leave fragments, so lead-shot game is best avoided.",
    safeWhen: "Choose lead-free game and cook thoroughly.",
    aliases: ["venison", "rabbit", "pheasant", "wild boar"],
    source: "NHS",
    category: "Meat & eggs",
  },
  {
    name: "Pineapple",
    verdict: "safe",
    summary: "Yes — pineapple is fine; the idea that it causes miscarriage is a myth in normal amounts.",
    why: "You would have to eat an enormous, unrealistic quantity of pineapple cores for the enzyme bromelain to have any effect. Eaten normally, it’s just fruit.",
    aliases: ["bromelain"],
    source: "Mayo Clinic",
    category: "Produce & other",
  },
  {
    name: "Papaya",
    verdict: "caution",
    summary: "Ripe papaya is fine; unripe or semi-ripe (green) papaya is traditionally avoided.",
    why: "Green papaya contains latex that, in theory, could stimulate contractions. Fully ripe papaya doesn’t have meaningful amounts and is fine in moderation.",
    safeWhen: "Choose fully ripe papaya and enjoy it in normal amounts.",
    aliases: ["green papaya", "pawpaw"],
    category: "Produce & other",
  },
  {
    name: "Pre-cut and pre-packaged fruit",
    verdict: "caution",
    summary: "Fresher is safer — eat it soon, since cut surfaces can grow listeria over time.",
    why: "Once fruit is cut, bacteria can grow on the exposed flesh, especially if it sits warm. Whole fruit you cut yourself and eat promptly is lower risk.",
    safeWhen: "Buy well-chilled, eat soon, or cut your own and refrigerate.",
    aliases: ["fruit salad", "cut melon", "pre-cut fruit"],
    source: "FDA",
    category: "Produce & other",
  },
  {
    name: "Tofu and soy",
    verdict: "safe",
    summary: "Yes — tofu and soy foods are a fine source of protein in pregnancy.",
    why: "Tofu, edamame, tempeh, and soy milk are well tolerated and nutritious. There’s no need to avoid soy in normal dietary amounts.",
    aliases: ["soy", "edamame", "tempeh", "soya", "soy milk"],
    category: "Produce & other",
  },
  {
    name: "Black licorice",
    verdict: "caution",
    summary: "Occasional is fine; avoid eating large amounts of real (glycyrrhizin) licorice regularly.",
    why: "A compound in real black licorice, glycyrrhizin, has been linked in studies to higher amounts to effects on the developing baby. Most candy \"licorice\" has little or none.",
    safeWhen: "Keep real black licorice occasional rather than a daily habit.",
    aliases: ["liquorice", "glycyrrhizin"],
    source: "ACOG",
    category: "Produce & other",
  },
  {
    name: "Ginger",
    verdict: "safe",
    summary: "Yes — ginger in food and tea amounts is fine and may ease nausea.",
    why: "Ginger has reassuring evidence for calming pregnancy nausea and is safe in culinary and tea quantities. Very high supplement doses are a different matter.",
    safeWhen: "Stick to food, tea, or modest amounts rather than high-dose supplements.",
    aliases: ["ginger tea", "ginger ale"],
    source: "Mayo Clinic",
    category: "Produce & other",
  },
  {
    name: "Cinnamon and cooking spices",
    verdict: "safe",
    summary: "Yes — spices used to flavour food are fine.",
    why: "Everyday culinary spices like cinnamon are safe in the amounts used in cooking. Concentrated medicinal or supplement doses aren’t the same and should be checked.",
    safeWhen: "Use as you normally would in food; avoid concentrated supplements.",
    aliases: ["cinnamon", "nutmeg", "turmeric", "spices"],
    category: "Produce & other",
  },
  {
    name: "Cannabis and CBD",
    verdict: "avoid",
    summary: "Avoid all forms — smoked, edible, or CBD — during pregnancy.",
    why: "Cannabis and CBD can reach the baby and have been linked to effects on development. No amount has been established as safe in pregnancy.",
    safeWhen: "Talk with your provider about safer options for whatever you’re using it for.",
    aliases: ["weed", "marijuana", "thc", "cbd", "edibles"],
    source: "ACOG",
    category: "Produce & other",
  },
  {
    name: "Raw or undercooked sprouted grains",
    verdict: "safe",
    summary: "Sprouted-grain bread and cooked sprouted grains are fine — it’s raw bean sprouts that are the issue.",
    why: "Baking and cooking handle any bacteria in sprouted grains. The specific concern is with raw sprouts (like alfalfa or mung bean) eaten uncooked.",
    safeWhen: "Eat sprouted grains cooked or baked; cook fresh sprouts until steaming.",
    aliases: ["sprouted bread", "ezekiel bread"],
    category: "Produce & other",
  },
  {
    name: "Chocolate",
    verdict: "safe",
    summary: "Yes — chocolate is fine; just remember dark chocolate has some caffeine.",
    why: "Chocolate is a treat, not a hazard. Dark chocolate carries more caffeine than milk chocolate, so very large amounts count toward your caffeine limit.",
    safeWhen: "Enjoy in normal amounts and keep total caffeine under ~200 mg a day.",
    aliases: ["dark chocolate", "milk chocolate"],
    category: "Produce & other",
  },
];

const VERDICT_META = {
  safe:    { label: 'Generally safe', headline: 'Yes \u2014 generally safe', cls: 'safe' },
  caution: { label: 'In moderation', headline: 'With some care', cls: 'caution' },
  avoid:   { label: 'Best avoided', headline: 'Better to skip this one', cls: 'avoid' },
};

// Ranked search: name-prefix first, then name-contains, then alias matches.
function foodSearch(query) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return FOOD_DB;
  const starts = [], nameContains = [], aliasContains = [];
  for (const item of FOOD_DB) {
    const name = item.name.toLowerCase();
    if (name.startsWith(q)) starts.push(item);
    else if (name.includes(q)) nameContains.push(item);
    else {
      const terms = [item.name, ...(item.aliases || [])].map((t) => t.toLowerCase());
      if (terms.some((t) => t.includes(q) || q.includes(t))) aliasContains.push(item);
    }
  }
  return [...starts, ...nameContains, ...aliasContains];
}
