// listTemplates.js
// Starting points for the Lists tab. Each template seeds a named list with
// common items so nothing important is forgotten — but every item is editable,
// and people can add their own or make lists from scratch. Suggestions are
// generous on purpose: blind spots are exactly what a checklist should catch.

const LIST_TEMPLATES = [
  {
    name: 'Hospital bag',
    blurb: 'What to pack for the big day.',
    items: [
      'Photo ID and insurance card',
      'Maternity notes / paperwork',
      'A copy of your birth plan',
      'Phone and a long charging cable',
      'Comfortable going-home outfit',
      'Robe, slippers, warm socks',
      'Toiletries and lip balm',
      'Hair ties and a brush',
      'Nursing bras',
      'Maternity pads',
      'Snacks and a water bottle',
      'Your own pillow and a cozy blanket',
      'Glasses or contact supplies',
      'Going-home outfit for baby',
      'Swaddle or blanket for baby',
      'Hat, socks, and mittens for baby',
      'Installed, rear-facing car seat',
      'Newborn diapers and wipes',
      'Partner: snacks, change of clothes, charger',
    ],
  },
  {
    name: 'Birth preferences',
    blurb: 'A flexible guide for your care team \u2014 not a contract.',
    items: [
      'Partner with me throughout',
      'Dim, calm lighting',
      'My own music or playlist',
      'Freedom to move during labor',
      'Open to all pain-relief options',
      'Prefer unmedicated if possible',
      'Epidural',
      'Water or birth pool',
      'Intermittent monitoring if possible',
      'Whatever pushing position feels right',
      'Delayed cord clamping',
      'Immediate skin-to-skin',
      'Partner cuts the cord',
      'Plan to breastfeed',
      'Lactation support, please',
      'Explain interventions before they happen',
      'If a cesarean: partner present and skin-to-skin if possible',
    ],
  },
  {
    name: 'Questions for the doctor',
    blurb: 'Bring these to your next appointment.',
    items: [
      'Is my weight gain on track?',
      'What foods or activities should I avoid now?',
      'Which symptoms should I call about?',
      'When is my next scan or test?',
      'What are my options for pain relief?',
      'Is my birth plan realistic here?',
      'What happens if I go past my due date?',
      'How do I know when it\u2019s time to come in?',
    ],
  },
  {
    name: 'Baby registry',
    blurb: 'The essentials people actually use.',
    items: [
      'Rear-facing infant car seat',
      'Stroller (car-seat compatible)',
      'Crib or bassinet and firm mattress',
      'Fitted crib sheets',
      'Swaddles and sleep sacks',
      'Diapers (newborn and size 1) and wipes',
      'Changing pad',
      'Bottles and a drying rack',
      'Breast pump (check your insurance)',
      'Baby carrier or wrap',
      'Bouncer or swing',
      'Onesies and footed sleepers',
      'Burp cloths and bibs',
      'Baby bath tub and hooded towels',
      'Nail clippers and a baby thermometer',
      'White-noise machine',
    ],
  },
  {
    name: 'Nursery',
    blurb: 'Setting up baby\u2019s space.',
    items: [
      'Crib or bassinet',
      'Firm mattress and 2\u20133 fitted sheets',
      'Dresser or storage',
      'Changing table or pad',
      'Diaper pail',
      'Blackout curtains',
      'Night light',
      'Comfortable chair for feeding',
      'Baby monitor',
      'Laundry basket / hamper',
      'Wall decor and a soft rug',
    ],
  },
  {
    name: 'Postpartum for mom',
    blurb: 'Caring for yourself after birth.',
    items: [
      'Maternity / postpartum pads',
      'Comfortable high-waisted underwear',
      'Peri bottle',
      'Witch-hazel pads or padsicles',
      'Pain relief your provider approves',
      'Nursing pads and nipple cream',
      'Loose, comfortable clothes',
      'Easy snacks and a big water bottle',
      'Stool softener (ask your provider)',
      'A support person lined up',
    ],
  },
];

// Names already used can be filtered out when offering templates again.
function templateByName(name) {
  return LIST_TEMPLATES.find((t) => t.name === name) || null;
}
