// weekContent.js
// Week-by-week pregnancy content for weeks 4-40, ported from the native Bloom
// app. Original content written from public medical consensus (ACOG, AAP, Mayo
// Clinic, NHS, NIH/MedlinePlus, INTERGROWTH-21st and WHO growth standards).
// Population averages; every pregnancy varies. Informational only.
//
// Length is crown-to-rump through ~week 19 and crown-to-heel from week 20.

const WEEK_CONTENT = [
  {
    week: 4,
    fruit: "a poppy seed",
    emoji: "🌱",
    lengthCm: 0.1,
    baby: "The embryo has implanted and the earliest building blocks of the nervous system, skin, and organs are forming.",
    body: "You may not feel different yet, or you might notice tender breasts and a missed period. The pregnancy hormone hCG is rising, which is what a pregnancy test detects.",
    encouragement: "This is the very beginning of an incredible journey. One day at a time — you've got this.",
    facts: [
      { text: "A home pregnancy test measures hCG, a hormone the developing placenta produces. Levels roughly double every two to three days in early pregnancy.", source: "Mayo Clinic" },
      { text: "Taking a prenatal vitamin with at least 400 micrograms of folic acid helps the baby's neural tube form properly. Starting early matters most in these first weeks.", source: "ACOG" },
      { text: "Your due date is counted from the first day of your last period, which means you are considered four weeks pregnant even though conception was about two weeks ago." },
    ],
  },
  {
    week: 5,
    fruit: "a sesame seed",
    emoji: "🟤",
    lengthCm: 0.2,
    baby: "The neural tube, which becomes the brain and spinal cord, is closing. The early heart is forming and may begin to pulse.",
    body: "Rising hormones can bring fatigue, tender breasts, and the first waves of nausea. Many people feel more tired than they expect — your body is doing enormous work.",
    encouragement: "Feeling exhausted already? That is your body building a whole new life. Rest when you can; it is productive, not lazy.",
    facts: [
      { text: "The early heart begins as a simple tube and starts to pulse around now, though it is far too faint to hear yet." },
      { text: "Fatigue in early pregnancy is partly driven by a surge in progesterone, which has a naturally sedating effect.", source: "Mayo Clinic" },
      { text: "If you take any regular medications, this is a good time to check with your provider about which are safe to continue.", source: "ACOG" },
    ],
  },
  {
    week: 6,
    fruit: "a sweet pea",
    emoji: "🫛",
    lengthCm: 0.5,
    baby: "A heartbeat may be visible on an early ultrasound. Tiny buds that will become arms and legs are appearing, and the face is starting to take shape.",
    body: "Morning sickness can arrive in earnest and may strike at any time of day, not just mornings. Heightened smell and food aversions are common and normal.",
    encouragement: "Nausea, as miserable as it is, is often a sign of a strong, rising pregnancy hormone. You are doing great.",
    facts: [
      { text: "Despite the name, \"morning sickness\" can happen any time of day. For most people it eases by the second trimester.", source: "NHS" },
      { text: "Eating small, frequent meals and keeping plain crackers nearby can take the edge off nausea by keeping your stomach from getting completely empty.", source: "Mayo Clinic" },
      { text: "The blood-volume increase that supports your pregnancy is already beginning, and will eventually rise by nearly half above your pre-pregnancy level.", source: "ACOG" },
      { text: "Ginger has some evidence behind it for easing pregnancy nausea and is considered safe in food amounts for most people." },
    ],
  },
  {
    week: 7,
    fruit: "a blueberry",
    emoji: "🫐",
    lengthCm: 1.0,
    baby: "The brain is growing rapidly and the limb buds are lengthening. Early kidneys and the beginnings of hands and feet are forming.",
    body: "Frequent urination often begins now, driven by hormones and increased blood flow to your kidneys — not yet by the baby's size. Fatigue may be peaking.",
    encouragement: "Running to the bathroom constantly? It is one of the earliest, quirkiest signs your body is adapting beautifully.",
    facts: [
      { text: "Early frequent urination comes from increased blood flow to your kidneys, which are already filtering more fluid than usual.", source: "Mayo Clinic" },
      { text: "The baby's brain is producing new cells at a remarkable pace this trimester." },
      { text: "Staying hydrated actually helps with both fatigue and nausea, even though it means more bathroom trips." },
    ],
  },
  {
    week: 8,
    fruit: "a cherry",
    emoji: "🍒",
    lengthCm: 1.6,
    baby: "Fingers and toes are starting to form, though still webbed. The major organs are establishing, and tiny movements begin, far too small to feel.",
    body: "Many people have their first prenatal appointment around now. Bloating, food aversions, and tender breasts are common. Your uterus is about the size of a large orange.",
    encouragement: "Your first appointment is a big milestone. Write down any questions beforehand — no question is too small to ask.",
    facts: [
      { text: "The first prenatal visit is usually the longest, covering health history, due-date confirmation, and baseline bloodwork.", source: "ACOG" },
      { text: "The baby is already making tiny, spontaneous movements, though they are far too small for you to feel for many weeks." },
      { text: "Tender, fuller breasts are one of the body's earliest preparations for milk production, driven by rising estrogen and progesterone.", source: "Mayo Clinic" },
    ],
  },
  {
    week: 9,
    fruit: "a grape",
    emoji: "🍇",
    lengthCm: 2.3,
    baby: "The embryo is becoming recognizably human in shape. The heart has divided into chambers and beats quickly, and essential organs continue to develop.",
    body: "Hormonal shifts may bring mood swings — feeling weepy or irritable is completely normal. Your breasts may continue to feel full as they prepare for the months ahead.",
    encouragement: "Riding an emotional rollercoaster? Pregnancy hormones are powerful. Be as gentle with yourself as you would be with a friend.",
    facts: [
      { text: "The baby's heart now beats roughly twice as fast as yours, often around 170 beats per minute at this stage." },
      { text: "Mood swings are partly hormonal and partly the natural weight of a major life change. Both are valid reasons to feel a lot at once.", source: "NHS" },
      { text: "The embryo officially becomes a fetus at the end of week 10, marking the close of the most critical period of organ formation." },
    ],
  },
  {
    week: 10,
    fruit: "a strawberry",
    emoji: "🍓",
    lengthCm: 3.1,
    weightG: 4.0,
    baby: "The most critical period of organ formation is complete and the baby is now officially a fetus. Tiny nails begin to form and joints can bend.",
    body: "Some early symptoms may start to ease over the coming weeks. You might notice your waistband getting snug, though a visible bump is usually still weeks away for a first pregnancy.",
    encouragement: "You're nearly through the first trimester. Each day is one more day of growth and one step closer to meeting your baby.",
    facts: [
      { text: "Now that the major organs are formed, the coming weeks are mostly about growth and refinement rather than building new structures." },
      { text: "Non-invasive prenatal testing (NIPT), a blood test that can screen for certain conditions and reveal sex, can typically be done from around 10 weeks.", source: "ACOG" },
      { text: "Tiny fingernails and the beginnings of teeth under the gums are forming this week." },
    ],
  },
  {
    week: 11,
    fruit: "a plum",
    emoji: "🟣",
    lengthCm: 4.1,
    weightG: 7.0,
    baby: "The baby is moving and stretching, though still unfelt. Bones are beginning to harden and tooth buds are forming beneath the gums.",
    body: "Appetite may return as nausea eases. Some people notice their skin or hair changing — thicker hair and a brighter complexion are common pregnancy effects.",
    encouragement: "If your appetite is coming back, enjoy it. Nourishing yourself is one of the kindest things you can do for both of you.",
    facts: [
      { text: "Hair often seems thicker in pregnancy because higher estrogen slows the normal rate of shedding, so you lose less than usual.", source: "Mayo Clinic" },
      { text: "The baby can already open and close its hands and may begin to hiccup, though you won't feel it yet." },
      { text: "Many providers can detect the baby's heartbeat with a handheld Doppler around 10 to 12 weeks." },
    ],
  },
  {
    week: 12,
    fruit: "a kiwi",
    emoji: "🥝",
    lengthCm: 5.4,
    weightG: 14.0,
    baby: "Reflexes are developing; the fingers may open and close. The face has settled into its features, and vital systems are formed and beginning to function.",
    body: "The end of the first trimester is near, and for many the toughest symptoms begin to lift. Your uterus is growing up out of your pelvis, so the bump may start to show soon.",
    encouragement: "You made it through the first trimester — a genuine milestone. The second trimester is often the most comfortable stretch ahead.",
    facts: [
      { text: "The risk of miscarriage drops significantly after the first trimester, which is why many people choose to share their news around now.", source: "ACOG" },
      { text: "The baby already has unique fingerprints forming, and the kidneys are beginning to produce urine into the amniotic fluid." },
      { text: "The first-trimester combined screening, an optional ultrasound and blood test, is typically offered between weeks 11 and 13.", source: "ACOG" },
    ],
  },
  {
    week: 13,
    fruit: "a fig",
    emoji: "🟣",
    lengthCm: 7.4,
    weightG: 23.0,
    baby: "Vocal cords are forming and unique fingerprints have appeared. The intestines, which developed near the umbilical cord, have moved into the abdomen.",
    body: "The second trimester begins — often called the \"honeymoon\" phase. Energy frequently improves, nausea typically fades, and many people start to feel more like themselves.",
    encouragement: "Welcome to the second trimester. Many people find their energy and appetite return now — a well-earned reprieve.",
    facts: [
      { text: "The placenta is now fully formed and doing the work of delivering oxygen and nutrients while removing waste." },
      { text: "The baby can swallow amniotic fluid and is starting to make sucking motions, practicing for feeding after birth." },
      { text: "Many people feel a noticeable lift in energy this trimester as the placenta takes over hormone production from the ovaries.", source: "Mayo Clinic" },
    ],
  },
  {
    week: 14,
    fruit: "a peach",
    emoji: "🍑",
    lengthCm: 8.7,
    weightG: 43.0,
    baby: "The baby can squint, frown, and make facial expressions. Fine hair called lanugo begins to cover the body, and the kidneys are producing urine.",
    body: "A pregnant glow may appear as blood flow to your skin increases. Some aches low in the abdomen come from the round ligaments stretching as your uterus grows.",
    encouragement: "That pregnancy glow people mention? It's real — more blood flow to your skin. Wear it proudly.",
    facts: [
      { text: "The \"pregnancy glow\" is partly increased blood flow to the skin and partly oil glands working a little harder.", source: "Mayo Clinic" },
      { text: "Round ligament pain — a quick pull or ache low in the belly when you move — is a normal result of ligaments stretching to support a growing uterus.", source: "ACOG" },
      { text: "The baby is now developing the muscles needed for facial expressions and can already make squinting and frowning movements." },
    ],
  },
  {
    week: 15,
    fruit: "an apple",
    emoji: "🍎",
    lengthCm: 10.1,
    weightG: 70.0,
    baby: "The baby is forming taste buds and can sense light through closed eyelids. The legs are now growing longer than the arms.",
    body: "Nasal congestion and the occasional nosebleed can happen as blood volume rises and tissues swell — a normal and harmless effect. The bump may be starting to show.",
    encouragement: "Your body is making more blood than ever to nourish your baby. A stuffy nose is a small, normal price for that incredible work.",
    facts: [
      { text: "A stuffy nose in pregnancy, sometimes called pregnancy rhinitis, comes from increased blood flow swelling the nasal tissues. It is harmless and eases after birth.", source: "NHS" },
      { text: "The baby can now sense light through the still-closed eyelids and may move toward a bright light held to the belly later on." },
      { text: "Your blood volume is climbing toward a peak of nearly 50 percent above pre-pregnancy levels, which supports the placenta and baby.", source: "ACOG" },
    ],
  },
  {
    week: 16,
    fruit: "an orange",
    emoji: "🍊",
    lengthCm: 11.6,
    weightG: 100.0,
    baby: "The baby can make sucking motions and the heart is pumping a considerable amount of blood each day. The eyes are beginning slow side-to-side movements.",
    body: "Some people feel the first faint flutters of movement, called quickening — often described as bubbles or a light tickle. It is usually later for a first pregnancy.",
    encouragement: "Those first flutters can be easy to miss. Whether you feel them now or in a few weeks, your baby is moving and growing right on schedule.",
    facts: [
      { text: "Early movements, called quickening, often feel like gas bubbles or a gentle flutter before they become unmistakable kicks.", source: "Mayo Clinic" },
      { text: "First-time mothers often notice movement later, around 18 to 22 weeks, simply because they don't yet know what to feel for." },
      { text: "The baby's heart is now pumping roughly 24 liters of blood a day, and that volume keeps rising as it grows." },
    ],
  },
  {
    week: 17,
    fruit: "an onion",
    emoji: "🧅",
    lengthCm: 13.0,
    weightG: 140.0,
    baby: "A protective coating called vernix begins to form on the skin. The skeleton is shifting from soft cartilage to bone, and fat stores are starting.",
    body: "Your center of gravity is shifting as your uterus grows, which can affect balance. A stronger appetite and occasional dizziness are common.",
    encouragement: "Feeling a little off balance? Your body is rearranging itself to carry your baby. Move a little slower and trust yourself.",
    facts: [
      { text: "Dizziness can happen because pregnancy hormones relax blood vessels, which can briefly lower blood pressure. Rising slowly from sitting helps.", source: "ACOG" },
      { text: "Vernix, a waxy white coating, is forming to protect the baby's skin from the constant exposure to amniotic fluid." },
      { text: "The baby's skeleton is hardening from cartilage into bone, a process that continues all the way to birth and beyond." },
    ],
  },
  {
    week: 18,
    fruit: "a bell pepper",
    emoji: "🫑",
    lengthCm: 14.2,
    weightG: 190.0,
    baby: "The ears have moved into position and the baby may begin to hear sounds. Nerves are gaining a protective coating, and movements are growing more coordinated.",
    body: "The mid-pregnancy anatomy ultrasound often happens around now. Backaches may begin as your posture adjusts; supportive shoes and gentle stretching can help.",
    encouragement: "The anatomy scan is a chance to see how beautifully your baby is growing. It's one of the most memorable moments of pregnancy.",
    facts: [
      { text: "The detailed anatomy ultrasound, usually done between 18 and 22 weeks, checks the baby's organs and growth and can often reveal the sex.", source: "ACOG" },
      { text: "The baby may now hear muffled sounds, including your heartbeat, your voice, and the rumble of your digestion." },
      { text: "Lower back pain is common as the growing uterus shifts your posture and pregnancy hormones loosen the joints in your pelvis.", source: "Mayo Clinic" },
    ],
  },
  {
    week: 19,
    fruit: "a mango",
    emoji: "🥭",
    lengthCm: 15.3,
    weightG: 240.0,
    baby: "Vernix now coats the skin to protect it in the fluid. The senses are growing more capable, and in girls the reproductive system is well developed.",
    body: "Round ligament pain and leg cramps can appear. Skin changes such as a darker line down the abdomen, called the linea nigra, are common and fade after birth.",
    encouragement: "Every stretch mark and new line is a map of the extraordinary thing your body is doing. They tell a story worth being proud of.",
    facts: [
      { text: "The linea nigra, a dark line down the belly, is caused by pregnancy hormones increasing pigment. It usually fades in the months after birth.", source: "Mayo Clinic" },
      { text: "Leg cramps, often at night, are common in later pregnancy. Gentle stretching before bed and staying hydrated can help." },
      { text: "The baby's senses — taste, smell, hearing, sight, and touch — are developing in dedicated regions of the brain this trimester." },
    ],
  },
  {
    week: 20,
    fruit: "a pomegranate",
    emoji: "🔴",
    lengthCm: 25.6,
    weightG: 300.0,
    headToHeel: true,
    baby: "The halfway point. The baby is now measured head to heel as the legs extend. It is swallowing more and producing the first stool, called meconium.",
    body: "Movements are often clearly felt by now. The top of your uterus reaches your navel, and your bump is usually visible. Many feel a surge of energy and connection.",
    encouragement: "Halfway there! Your body has grown your baby from a single cell to this amazing milestone. Take a moment to feel proud of how far you've both come.",
    facts: [
      { text: "At 20 weeks the baby's measurement switches from crown-to-rump to head-to-heel, which is why the length appears to jump." },
      { text: "Meconium, the baby's first stool, is building up in the intestines and is usually passed in the first day or two after birth." },
      { text: "The top of the uterus reaches the level of the navel around now — a handy landmark providers use to track growth.", source: "ACOG" },
    ],
  },
  {
    week: 21,
    fruit: "a grapefruit",
    emoji: "🍊",
    lengthCm: 26.7,
    weightG: 360.0,
    headToHeel: true,
    baby: "The baby is becoming more active, with movements you can feel. The digestive system is practicing by absorbing small amounts of sugars from the swallowed fluid.",
    body: "Appetite is often strong now. You may notice your belly button changing shape and mild swelling in your feet by the end of the day.",
    encouragement: "Your baby is busy and active in there. Those kicks and rolls are a wonderful sign of a thriving little one.",
    facts: [
      { text: "The baby now has regular periods of activity and rest, and you may start to notice patterns in when it moves." },
      { text: "Mild swelling in the feet and ankles, especially later in the day, is normal. Putting your feet up and staying hydrated helps.", source: "NHS" },
      { text: "Taste buds are now developed, and flavors from what you eat reach the amniotic fluid the baby swallows." },
    ],
  },
  {
    week: 22,
    fruit: "an eggplant",
    emoji: "🍆",
    lengthCm: 27.8,
    weightG: 430.0,
    headToHeel: true,
    baby: "The senses are sharpening; the baby can perceive touch and may respond to sound. The lips and eyebrows are becoming more distinct.",
    body: "Stretch marks may appear as the skin expands — they fade over time and are extremely common. Your hair may feel thicker and your nails may grow faster.",
    encouragement: "Stretch marks are badges of motherhood that the vast majority of mothers share. Your changing body is doing something amazing.",
    facts: [
      { text: "Stretch marks form in the deeper layer of skin as it stretches. Most fade to faint silvery lines after pregnancy.", source: "Mayo Clinic" },
      { text: "The baby can now feel its own face and grasp the umbilical cord as its sense of touch develops." },
      { text: "Eyebrows and the fine details of the face are becoming more defined this week." },
    ],
  },
  {
    week: 23,
    fruit: "a pomelo",
    emoji: "🍊",
    lengthCm: 28.9,
    weightG: 500.0,
    headToHeel: true,
    baby: "The lungs are developing the blood vessels they will need to breathe. The baby may begin to have regular periods of sleep and wakefulness.",
    body: "Swelling in the ankles and feet is common. Gentle practice contractions, called Braxton-Hicks, may begin — they are usually painless and irregular.",
    encouragement: "Braxton-Hicks contractions are your body rehearsing for the big day. They're a normal, healthy part of getting ready.",
    facts: [
      { text: "Braxton-Hicks contractions are irregular, usually painless tightenings that help tone the uterus. Unlike labor, they don't grow longer, stronger, and closer together.", source: "ACOG" },
      { text: "The baby's lungs are building the network of tiny blood vessels needed to exchange oxygen after birth." },
      { text: "If contractions become regular and frequent before 37 weeks, it's worth calling your provider to be safe.", source: "ACOG" },
    ],
  },
  {
    week: 24,
    fruit: "a cantaloupe",
    emoji: "🍈",
    lengthCm: 30.0,
    weightG: 600.0,
    headToHeel: true,
    baby: "The baby reaches an important milestone of viability this week, though much growing remains. The face is fully formed and the inner ear is controlling balance.",
    body: "A glucose screening for gestational diabetes is often scheduled around now. The skin on your belly may feel itchy as it stretches; unscented moisturizer can help.",
    encouragement: "Reaching this point is a meaningful milestone. Your baby is growing stronger every single day.",
    facts: [
      { text: "The glucose screening checks how your body handles sugar and screens for gestational diabetes, which is common and very manageable.", source: "ACOG" },
      { text: "The inner ear, which governs balance, is now fully developed, so the baby can sense whether it is upside down in the womb." },
      { text: "Persistent, intense itching without a rash, especially on the hands and feet, is worth mentioning to your provider.", source: "NHS" },
    ],
  },
  {
    week: 25,
    fruit: "a coconut",
    emoji: "🥥",
    lengthCm: 34.6,
    weightG: 660.0,
    headToHeel: true,
    baby: "The baby is gaining baby fat, making the skin smoother. Hair is growing and may have color and texture. The hands are now fully developed and active.",
    body: "The third trimester is approaching. Heartburn and trouble finding a comfortable sleep position can increase. Sleeping on your side is recommended from now on.",
    encouragement: "Sleep is getting trickier, but every rest counts. Side-sleeping with a pillow between your knees can make a real difference.",
    facts: [
      { text: "Sleeping on your side, ideally the left, improves blood flow to the baby and is recommended in later pregnancy.", source: "ACOG" },
      { text: "The baby is filling out with fat that will help regulate body temperature after birth." },
      { text: "Heartburn is common as pregnancy hormones relax the valve at the top of the stomach. Smaller meals and staying upright after eating help.", source: "Mayo Clinic" },
    ],
  },
  {
    week: 26,
    fruit: "a cherimoya",
    emoji: "🟢",
    lengthCm: 35.6,
    weightG: 760.0,
    headToHeel: true,
    baby: "The eyes are beginning to open after weeks of being fused shut. The lungs are practicing breathing movements, drawing in amniotic fluid.",
    body: "Your blood pressure may rise slightly, and appointments will monitor it. The baby's kicks are often strong enough now for others to feel with a hand on your belly.",
    encouragement: "Sharing those kicks with your partner is one of pregnancy's sweetest joys. Your baby is making its presence known.",
    facts: [
      { text: "The baby's eyes are starting to open, and it can blink. The eye color at birth may still change in the first year." },
      { text: "Providers watch blood pressure closely in the third trimester to catch preeclampsia early; it's a routine and important check.", source: "ACOG" },
      { text: "The baby is practicing breathing movements, inhaling and exhaling amniotic fluid to strengthen the lungs." },
    ],
  },
  {
    week: 27,
    fruit: "a honeydew melon",
    emoji: "🍈",
    lengthCm: 36.6,
    weightG: 875.0,
    headToHeel: true,
    baby: "The third trimester begins. The brain is very active and the baby may begin to recognize familiar voices. Sleep cycles, including dreaming sleep, are emerging.",
    body: "Leg cramps and backaches can become more frequent. Counting the baby's movements each day becomes a useful habit and a reassuring way to stay connected.",
    encouragement: "Welcome to the home stretch — the third trimester. Your baby can hear and may even know your voice now.",
    facts: [
      { text: "Research suggests babies can recognize their mother's voice before birth and may be calmed by it after.", source: "Mayo Clinic" },
      { text: "Counting kicks — noticing how long it takes to feel ten movements — is a simple daily way to monitor the baby's wellbeing.", source: "ACOG" },
      { text: "The baby's brain is developing the folds and grooves that dramatically increase its surface area and capacity." },
    ],
  },
  {
    week: 28,
    fruit: "a papaya",
    emoji: "🥭",
    lengthCm: 37.6,
    weightG: 1000.0,
    headToHeel: true,
    baby: "The baby can blink and has eyelashes. The lungs are maturing and would have a good chance of functioning with support. Fat continues to fill out the body.",
    body: "Prenatal visits typically become more frequent now. Shortness of breath can occur as your uterus presses upward against your diaphragm. It eases when the baby drops later.",
    encouragement: "A little breathless? Your baby is growing up toward your ribs. It's a sign of a healthy, growing little one.",
    facts: [
      { text: "Shortness of breath happens as the growing uterus pushes the diaphragm up by several centimeters, leaving less room for the lungs to expand.", source: "ACOG" },
      { text: "Visits usually move to every two weeks around now, then weekly in the final month, to monitor you and the baby more closely." },
      { text: "If your blood type is Rh-negative, you may receive a Rh immunoglobulin injection around this time to protect future pregnancies.", source: "ACOG" },
    ],
  },
  {
    week: 29,
    fruit: "a pineapple",
    emoji: "🍍",
    lengthCm: 38.6,
    weightG: 1150.0,
    headToHeel: true,
    baby: "Muscles and lungs continue to mature, and the head is growing to accommodate the developing brain. The baby is becoming more cramped as it grows.",
    body: "Increasing fatigue is normal as your body works harder. Iron needs are higher now to support the baby and your expanded blood supply; your provider may check your levels.",
    encouragement: "Tired again in the third trimester? That's your body carrying extra blood, extra weight, and a growing baby. Be kind to yourself.",
    facts: [
      { text: "Iron supports the extra red blood cells your body is making. Mild anemia is common in late pregnancy and is easily addressed.", source: "ACOG" },
      { text: "Pairing iron-rich foods with vitamin C, like citrus, helps your body absorb the iron more effectively.", source: "NHS" },
      { text: "The baby's bones are fully formed now but still soft, and it is drawing calcium from you to harden them." },
    ],
  },
  {
    week: 30,
    fruit: "an acorn squash",
    emoji: "🟢",
    lengthCm: 39.9,
    weightG: 1320.0,
    headToHeel: true,
    baby: "The soft lanugo hair begins to disappear as the baby's own brain takes over temperature regulation. Bone marrow is now fully producing red blood cells.",
    body: "Mood may shift with anticipation and discomfort. Trouble sleeping is common; a pregnancy pillow and a cooler room can help. Vivid dreams are also very normal.",
    encouragement: "Having strange, vivid dreams? They're a normal part of pregnancy. Your mind is processing this big, beautiful change.",
    facts: [
      { text: "Vivid or unusual dreams are common in pregnancy, linked to hormones and to more frequent waking, which makes dreams easier to remember.", source: "Mayo Clinic" },
      { text: "The baby's brain is now mature enough to help regulate its own body temperature, which is why the downy lanugo starts to shed." },
      { text: "Bone marrow has fully taken over production of red blood cells from the liver and spleen." },
    ],
  },
  {
    week: 31,
    fruit: "a sugar pie pumpkin",
    emoji: "🎃",
    lengthCm: 41.1,
    weightG: 1500.0,
    headToHeel: true,
    baby: "The baby can turn its head from side to side and is making fast breathing movements. Most major development is complete; the focus now is growth and weight gain.",
    body: "Braxton-Hicks contractions may grow more noticeable. Some people leak small amounts of colostrum, the nutrient-rich first milk — a normal sign your body is preparing.",
    encouragement: "Your body is already making your baby's first food. It knows exactly what to do, and so will you.",
    facts: [
      { text: "Colostrum, the thick first milk, is rich in antibodies and is produced for the first days after birth before mature milk comes in.", source: "NHS" },
      { text: "Leaking a little colostrum in late pregnancy is normal and is no indication of how much milk you'll make later." },
      { text: "The baby is now putting on weight steadily, gaining roughly 200 grams or more each week from here on." },
    ],
  },
  {
    week: 32,
    fruit: "a honeydew melon",
    emoji: "🍈",
    lengthCm: 42.4,
    weightG: 1700.0,
    headToHeel: true,
    baby: "The baby is practicing breathing, sucking, and swallowing in preparation for birth. Toenails and fingernails have finished growing, and the skin is less translucent.",
    body: "Heartburn and shortness of breath may peak as space grows tight. The baby often begins settling into a head-down position in preparation for birth.",
    encouragement: "Your baby is getting into position and practicing the skills it needs. You're both getting ready, together.",
    facts: [
      { text: "Most babies settle head-down by around 36 weeks, but at 32 weeks there is still plenty of room to turn.", source: "ACOG" },
      { text: "The baby now has working sleep and wake cycles and may startle at sudden loud noises." },
      { text: "Practicing breathing, sucking, and swallowing now builds the coordination the baby needs to feed after birth." },
    ],
  },
  {
    week: 33,
    fruit: "a butternut squash",
    emoji: "🟤",
    lengthCm: 43.7,
    weightG: 1920.0,
    headToHeel: true,
    baby: "The bones are hardening, though the skull stays soft and flexible for birth. The baby's immune system is developing as antibodies pass across the placenta.",
    body: "Aches, swelling, and fatigue often increase. Now is a good time to finalize a birth plan, pack a hospital bag, and install the car seat while you have energy.",
    encouragement: "Ticking things off your list brings real peace of mind. A little preparation now lets you relax into these final weeks.",
    facts: [
      { text: "Antibodies passing from you to the baby now provide protection in the first months of life until its own immune system matures.", source: "Mayo Clinic" },
      { text: "The skull bones stay unfused and flexible so the head can mold slightly to pass through the birth canal." },
      { text: "Packing a hospital bag and installing the car seat a few weeks early avoids a last-minute scramble if labor starts sooner than expected.", source: "ACOG" },
    ],
  },
  {
    week: 34,
    fruit: "a spaghetti squash",
    emoji: "🟡",
    lengthCm: 45.0,
    weightG: 2150.0,
    headToHeel: true,
    baby: "The lungs are nearly mature and the central nervous system is developing steadily. The baby's fat layers are rounding out the arms, legs, and face.",
    body: "Your vision may feel slightly blurry from fluid changes, which is usually temporary. Pelvic pressure can increase as the baby drops lower into position.",
    encouragement: "So close now. Every day your baby is getting rounder, stronger, and more ready to meet you.",
    facts: [
      { text: "Mild blurry vision can come from fluid retention changing the shape of the eye slightly. It typically resolves after birth.", source: "NHS" },
      { text: "The baby's lungs are producing more surfactant, the substance that keeps the tiny air sacs open for breathing." },
      { text: "Sudden severe swelling, a bad headache, or vision changes with spots should be reported to your provider promptly, as they can signal preeclampsia.", source: "ACOG" },
    ],
  },
  {
    week: 35,
    fruit: "a sugar baby watermelon",
    emoji: "🍉",
    lengthCm: 46.2,
    weightG: 2380.0,
    headToHeel: true,
    baby: "The baby is filling out and most systems are well developed, with the kidneys fully formed and the liver processing some waste. Space is now quite tight.",
    body: "Trips to the bathroom may increase again as the baby settles lower. A group B strep test is often done around this stage to guide care during labor.",
    encouragement: "Your baby is running out of room because it's grown so beautifully. The finish line is in sight.",
    facts: [
      { text: "The group B strep test is a simple swab; if positive, antibiotics during labor protect the baby. It's routine and common.", source: "ACOG" },
      { text: "Most of the baby's basic development is complete by now — these final weeks are about gaining weight and strength." },
      { text: "As the baby drops into the pelvis, you may breathe more easily but feel more pressure low down and need the bathroom more often." },
    ],
  },
  {
    week: 36,
    fruit: "a field pumpkin",
    emoji: "🎃",
    lengthCm: 47.4,
    weightG: 2620.0,
    headToHeel: true,
    baby: "The baby is likely head-down and getting into position for birth. The soft, downy lanugo and much of the vernix are being shed and swallowed.",
    body: "Weekly prenatal visits typically begin. Lightening — when the baby drops into the pelvis — can ease breathing but add pelvic pressure and waddling.",
    encouragement: "You're in the final month. Your body knows how to do this, and you are more ready than you feel.",
    facts: [
      { text: "At 36 weeks the baby is considered to be approaching full term; providers begin weekly checks to monitor the final stretch.", source: "ACOG" },
      { text: "\"Lightening\" is the term for the baby dropping lower into the pelvis, which often happens in the weeks before labor for first pregnancies." },
      { text: "The baby swallows lanugo and vernix it sheds, which becomes part of the first stool, meconium." },
    ],
  },
  {
    week: 37,
    fruit: "a jack-o'-lantern pumpkin",
    emoji: "🎃",
    lengthCm: 48.6,
    weightG: 2860.0,
    headToHeel: true,
    baby: "The baby is considered early term. It is practicing breathing and has a firm grasp. The brain and lungs continue maturing right up to birth.",
    body: "Signs of approaching labor may appear, such as the mucus plug passing or a burst of nesting energy. Every pregnancy and labor begins differently.",
    encouragement: "Early term and ready. Trust the process — your baby will choose the right moment to arrive.",
    facts: [
      { text: "At 37 weeks a baby is \"early term.\" The brain and lungs still benefit from any additional days inside, so labor is generally not induced without a reason before 39 weeks.", source: "ACOG" },
      { text: "The mucus plug, which seals the cervix, may come away days or weeks before labor; it doesn't necessarily mean labor is imminent." },
      { text: "A burst of energy and an urge to clean and organize — \"nesting\" — is commonly reported in the final weeks." },
    ],
  },
  {
    week: 38,
    fruit: "a Cinderella pumpkin",
    emoji: "🎃",
    lengthCm: 49.8,
    weightG: 3080.0,
    headToHeel: true,
    baby: "The baby has a firm grasp and its organs are ready for life outside the womb. The vernix and lanugo are nearly gone, and meconium fills the intestines.",
    body: "Watch for signs of labor: regular contractions that grow stronger, your water breaking, or a persistent low backache. Rest and conserve energy while you can.",
    encouragement: "Any day could be the day. You've carried and nurtured your baby to this point — what an extraordinary thing to have done.",
    facts: [
      { text: "Labor is most likely when contractions become regular and steadily grow longer, stronger, and closer together — unlike Braxton-Hicks.", source: "ACOG" },
      { text: "Only about 1 in 20 babies arrives on the exact due date; anytime from 37 to 42 weeks is considered normal timing." },
      { text: "If your water breaks, note the time, color, and amount, and contact your provider — labor often follows within hours.", source: "NHS" },
    ],
  },
  {
    week: 39,
    fruit: "a watermelon",
    emoji: "🍉",
    lengthCm: 50.7,
    weightG: 3290.0,
    headToHeel: true,
    baby: "The baby is full term. The lungs continue building surfactant, and a layer of fat is developing to help regulate body temperature after birth.",
    body: "Your cervix may begin to soften and open in preparation. Contractions that grow longer, stronger, and closer together signal active labor is on its way.",
    encouragement: "Full term and perfect. Your baby is ready whenever the moment comes — and so are you.",
    facts: [
      { text: "At 39 weeks the baby is full term, the point at which the lungs and brain are most ready for birth.", source: "ACOG" },
      { text: "The cervix softens, thins, and begins to open before labor; providers may describe this as effacement and dilation." },
      { text: "First labors often last longer than later ones; early labor in particular can unfold gradually over many hours." },
    ],
  },
  {
    week: 40,
    fruit: "a watermelon",
    emoji: "🍉",
    lengthCm: 51.2,
    weightG: 3460.0,
    headToHeel: true,
    baby: "Your due date is here, though only a small share of babies arrive exactly on it. The baby is fully developed and ready to meet you; arrival around now is normal.",
    body: "If labor hasn't begun, your provider will discuss monitoring and next steps. Trust your body, stay in close contact with your care team, and rest when you can.",
    encouragement: "You did it — you grew a whole person. Whenever your baby arrives, you are ready to be their parent.",
    facts: [
      { text: "Going a little past the due date is common, especially for a first baby. Providers monitor closely and discuss options if you pass 41 weeks.", source: "ACOG" },
      { text: "The due date is an estimate; a pregnancy is considered to last anywhere from 37 to 42 weeks normally." },
      { text: "After 41 weeks, providers typically offer extra monitoring and may discuss inducing labor to keep you and the baby safe.", source: "ACOG" },
    ],
  },
];

const WEEK_MIN = 4;
const WEEK_MAX = 40;

function weekContentFor(week) {
  const clamped = Math.max(WEEK_MIN, Math.min(WEEK_MAX, week));
  return WEEK_CONTENT.find((w) => w.week === clamped) || WEEK_CONTENT[0];
}

// ---------------------------------------------------------------------------
// Size themes. Fruit is the default (per-week fields above). The Sports theme
// maps each week to a ball of roughly matching size — a fun alternative the
// user can switch on in Settings. Stock ball emojis are used where they exist
// (ping pong, tennis, baseball, softball, soccer, volleyball, basketball); the
// rest fall back to a neutral ball placeholder and are good candidates for
// custom art (same image system as fruit: art/sport-NN.png).
// ---------------------------------------------------------------------------

const SPORT_COMPARISON = {
  4: { name: 'much smaller than a marble', emoji: '⚪', img: 'marble' },
  5: { name: 'smaller than a marble', emoji: '⚪', img: 'marble' },
  6: { name: 'smaller than a marble', emoji: '⚪', img: 'marble' },
  7: { name: 'slightly smaller than a marble', emoji: '⚪', img: 'marble' },
  8: { name: 'a marble', emoji: '⚪', img: 'marble' },
  9: { name: 'slightly larger than a marble', emoji: '⚪', img: 'marble' },
  10: { name: 'slightly smaller than a ping pong ball', emoji: '🏓', img: 'ping-pong-ball' },
  11: { name: 'a ping pong ball', emoji: '🏓', img: 'ping-pong-ball' },
  12: { name: 'a pool ball', emoji: '🎱', img: 'pool-ball' },
  13: { name: 'a tennis ball', emoji: '🎾', img: 'tennis-ball' },
  14: { name: 'a polo ball', emoji: '⚪', img: 'polo-ball' },
  15: { name: 'a softball', emoji: '🥎', img: 'softball' },
  16: { name: 'a bocce ball', emoji: '⚪', img: 'bocce-ball' },
  17: { name: 'slightly larger than a bocce ball', emoji: '⚪', img: 'bocce-ball' },
  18: { name: 'a rugby ball', emoji: '🏉', img: 'rugby-ball' },
  19: { name: 'a football', emoji: '🏈', img: 'football' },
  20: { name: 'a volleyball', emoji: '🏐', img: 'volleyball' },
  21: { name: 'a soccer ball', emoji: '⚽', img: 'soccer-ball' },
  22: { name: 'a netball', emoji: '⚪', img: 'netball' },
  23: { name: 'a bowling ball', emoji: '⚪', img: 'bowling-ball' },
  24: { name: 'slightly smaller than a basketball', emoji: '🏀', img: 'basketball' },
  25: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  26: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  27: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  28: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  29: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  30: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  31: { name: 'a basketball', emoji: '🏀', img: 'basketball' },
  32: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  33: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  34: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  35: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  36: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  37: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  38: { name: 'slightly larger than a basketball', emoji: '🏀', img: 'basketball' },
  39: { name: 'a curling stone', emoji: '⚪', img: 'curling-stone' },
  40: { name: 'a medicine ball', emoji: '⚪', img: 'medicine-ball' },
};

// Return { name, emoji } for the chosen theme ('fruit' | 'sport').
function comparisonFor(week, theme) {
  const info = weekContentFor(week);
  if (theme === 'sport') {
    const s = SPORT_COMPARISON[info.week];
    if (s) return { name: s.name, emoji: s.emoji, img: s.img };
  }
  return { name: info.fruit, emoji: info.emoji };
}
